import Head from "next/head";
import React from "react";
import About from "../components/About";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";

export default function about() {
  return (
    <div>
      <Head>
        <title>Dreamz | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Jost:wght@500;600;700&family=Open+Sans:wght@400;500&display=swap"
          rel="stylesheet"
        />

        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css"
          rel="stylesheet"
        />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css"
          rel="stylesheet"
        />
      </Head>
      <Navbar />
      <div
        class="container-fluid page-header mb-5 wow fadeIn"
        data-wow-delay="0.1s"
      >
        <div class="container">
          <h1 class="display-3 mb-4 animated slideInDown">About</h1>
          <nav aria-label="breadcrumb animated slideInDown">
            <ol class="breadcrumb mb-0">
              <li class="breadcrumb-item">
                <a href="#">Home</a>
              </li>
              <li class="breadcrumb-item">
                <a href="#">Pages</a>
              </li>
              <li class="breadcrumb-item active" aria-current="page">
                About
              </li>
            </ol>
          </nav>
        </div>
      </div>

      <About />

      <div className="container">
        <div className="row">
          <div className="col-md-6">
            Dreamz Limited is now available with the solutions to these problems
            and making those dreams and desires of the general public a reality
            with their quality, efficient, swift and satisfactory services to
            help manage time and save cash.{" "}
          </div>
          <div className="col-md-6">
            Get Your visas to any country of your choice and many more with us,
            send and receive parcels too and have us book your flight for you in
            any country of your choice and at the cheapest price available. We
            are here for you be it before, during, or after travel needs.
          </div>
        </div>
      </div>

      <Footer />
    </div>
  );
}
